Parque/urls.py
from django.contrib import admin
from django.urls import path, include
from App import views
from App.api.router import router_api


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='index'),
    path('proyectos/', views.ProyectosView.as_view(), name='proyectos'),
    path('crear/', views.ProyectoCreateView.as_view(), name='crear'),
    path('servicios/', views.ServiciosView.as_view(), name='servicios'),
    path('encuentros/', views.EncuentrosView.as_view(), name='encuentros'),
    path('api/',include(router_api.urls)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

App/api/models.py
from django.db import models

# Create your models here.

App/models.py
import random

from django.db import models


# Create your models here.
from django.db.models.functions import datetime
from django.utils.datetime_safe import date


class Proyecto(models.Model):
    nombre=models.CharField(max_length=250, verbose_name="Nombre del pipProyecto")
    descrip=models.TextField(max_length=250, verbose_name="Descripción del Proyecto")
    fecha_inicio=models.DateField(verbose_name="Fecha de Inicio")
    activo=models.BooleanField(default=False)
    imagen=models.ImageField(upload_to='proyecto/', null= True, blank=True)
    file=models.FileField(upload_to='proyecto/Anexos1', null=True, blank=True)
    programa = models.ForeignKey('self', on_delete=models.CASCADE, verbose_name="Programa", null=True, blank=True)


    def __str__(self):
        return self.nombre
    def porciento(self):
        return datetime.Now-self.fecha_inicio
    class Meta:
        verbose_name='Proyecto'
        verbose_name_plural='Proyectos'
        db_table='proyectos'


class Anexo(models.Model):
    proyecto = models.OneToOneField(
        Proyecto,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    nombre_programa = models.CharField(max_length=250, verbose_name="Nombre del Programa")
    nombre_proyecto = models.CharField(max_length=250, verbose_name="Nombre del proyecto")
    codigo_proyecto = models.CharField(max_length=250, verbose_name="Código del proyecto")
    clasificacion_proyecto = models.TextField(verbose_name="Clasificación del proyecto")
    prioridad_establecida= models.TextField(verbose_name="PRIORIDAD ESTABLECIDA AL NIVEL QUE RESPONDE")
    financiamiento= models.TextField(verbose_name="FINANCIAMIENTO")
    resumen= models.TextField(verbose_name="Reumen del Proyecto")
    problem_resolver= models.TextField(verbose_name="Problemas a resolver")
    contexto= models.TextField(verbose_name="CONTEXTO, ANTECEDENTES Y JUSTIFICACIÓN DE PROYECTO")
    beneficiarios= models.TextField(verbose_name="BENEFICIARIOS DIRECTOS")
    clientes= models.TextField(verbose_name="CLIENTES o USUARIOS")
    objetivog= models.TextField(verbose_name="OBJETIVO GENERAL")
    objetivoe= models.TextField(verbose_name="OBJETIVOS ESPECÍFICOS")
    resultados= models.TextField(verbose_name="RESULTADOS")
    salidas= models.TextField(verbose_name="SALIDAS")
    impactos= models.TextField(verbose_name="IMPACTOS")
    riesgo= models.TextField(verbose_name="RIESGO IDENTIFICADO")
    acci_mitagacion= models.TextField(verbose_name="ACCIONES MITIGACIÓN")
    metodologia= models.TextField(verbose_name="METODOLOGÍAS. TECNOLOGÍAS, NORMAS Y MÉTODOS")

    def __str__(self):
        return self.nombre
    class Meta:
        verbose_name='Anexo'
        verbose_name_plural='Anexos'
        db_table='anexos'

class Servicio(models.Model):
    nombre=models.CharField(max_length=250, verbose_name="Nombre del servicio")
    descrip=models.TextField(max_length=250, verbose_name="Descripción del servicio")
    activo=models.BooleanField(default=False)
    imagen=models.ImageField(upload_to='servicio/images', null= True, blank=True)
    file=models.FileField(upload_to='servicio/documento', null=True, blank=True)



    def __str__(self):
        return self.nombre
    class Meta:
        verbose_name='Servicio'
        verbose_name_plural='Servicios'
        db_table='servicios'

App/forms.py
from django.forms import ModelForm

from App.models import Proyecto
from App.models import Anexo
from App.models import Servicio


class ProyectoForm(ModelForm):
    class Meta:
        model=Proyecto
        fields='__all__'

class AnexoForm(ModelForm):
    class Meta:
        model = Anexo
        fields = '__all__'

class ServicioForm(ModelForm):
    class Meta:
        model = Servicio
        fields = '__all__'

App/api/views.py
from rest_framework.viewsets import ModelViewSet
from App.models import Proyecto, Servicio
from App.api.serializers import ProyectoSerializer, ServicioSerializer


# Create your views here.
class ProyectoApiViewSet(ModelViewSet):
    serializer_class = ProyectoSerializer
    queryset = Proyecto.objects.all()


class ServicioApiViewSet(ModelViewSet):
    serializer_class = ServicioSerializer
    queryset = Servicio.objects.all()

App/views.py
import random
from .services import get_username
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, CreateView

from App.forms import ProyectoForm
from App.models import Proyecto
from App.forms import AnexoForm
from App.models import Anexo
from App.forms import ServicioForm
from App.models import Servicio





class HomeView(ListView):
    model = Proyecto
    template_name = 'index.html'

    def get_queryset(self):
        return Proyecto.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['servicios'] = Servicio.objects.all()
        context['name']= get_username()
        return context

class ProyectoCreateView(CreateView):
    model = Proyecto
    form_class = ProyectoForm
    template_name = 'crear.html'

class ProyectosView(ListView):
        model = Proyecto
        template_name = 'proyectos.html'

        def get_queryset(self):
            return Proyecto.objects.all()


class EncuentrosView(ListView):
    model = Proyecto

    template_name = 'encuentros.html'

    def get_queryset(self):
        return Proyecto.objects.all()

class ServiciosView(ListView):
        model = Proyecto
        template_name = 'servicios.html'

        def get_queryset(self):
            return Servicio.objects.all()


class AnexoCreateView(CreateView):
    model = Anexo
    form_class = AnexoForm
    template_name = 'crear.html'

class ServicioCreateView(CreateView):
    model = Servicio
    form_class = ServicioForm
    template_name = 'crear.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Proyectos</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'agency/assets/índice.png' %}" />
        <!-- Google fonts-->
        <link href="{% static 'agency/css/font1.css'%}" rel="stylesheet" type="text/css" />
        <link href="{% static 'agency/css/font2.css'%}" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'agency/css/styles.css'%}" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'bootstrap-icons/bootstrap-icons.css' %}">
        <script type="text/javascript" src="{% static 'chart/chart.js' %}"></script>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
{#                <a class="navbar-brand" href="#page-top"><img src="{% static 'agency/assets/img/logo.png'%}" alt="..." /></a>#}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menú
                    <i class="bi bi-list toggle-sidebar-btn"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'proyectos' %}">Proyectos</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'servicios' %}">Servicios</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'encuentros' %}">Encuentros</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Crear, Desarrollar, Exportar</div>
                <div class="masthead-heading text-uppercase">CIENTEX Matanzas S.A.</div>
                <!--<a class="btn btn-outline-light btn-xl text-uppercase" href="#portfolio">Ver Proyectos</a>-->
            </div>
        </header>
        {% block 'contenido' %}
        {% endblock %}
        <!-- Bootstrap core JS-->
        <script src="{% static 'agency/js/js.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'agency/js/scripts.js'%}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="{% static 'agency/js/bootstrap.js'%}"></script>
    </body>
</html>

templates/crear.html
{% extends 'base.html' %}
{% load static %}
{% block 'contenido' %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
    <button type="submit" class="btn btn-success">Aceptar</button>
    </form>
{% endblock %}

templates/encuentros.html
{% extends 'base.html' %}
{% load static %}
{% block 'contenido' %}
        <!-- Portfolio Grid-->
        <section class="page-section bg-light" id="portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Encuentros</h2>
                </div>
                <div class="row">
                    {% for a in object_list %}

                    <div class="col-lg-4 col-sm-6 mb-4">
                        <!-- Portfolio item 1-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal{{ a.id }}">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="bi bi-search"></i></div>
                                </div>
                               {% if  a.imagen == " " %}
                                      <img class="img-fluid d-block mx-auto" style="height: 250px" src="/media/proyecto/proyecto.jpg" alt="..." />
                                    {% else %}
                                        <img class="img-fluid d-block mx-auto" style="height: 250px" src="/media/{{ a.imagen }}" alt="..." />
                                    {% endif %}
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">{{ a.nombre }}</div>
                            </div>
                        </div>
                    </div>

                    <div class="portfolio-modal modal fade" id="portfolioModal{{ a.id }}" tabindex="-1" role="dialog" aria-hidden="true">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="close-modal" data-bs-dismiss="modal"><img src="{% static 'agency/assets/img/close-icon.svg' %}" alt="Close modal" /></div>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <div class="modal-body">
                                    <!-- Project details-->
                                    <h2 class="text-uppercase">{{ a.nombre}}</h2>
                                     <img class="img-fluid d-block mx-auto" src="/media/proyecto/proyecto.jpg" alt="..." />
                                    <p>{{ a.descrip }}</p>
                                    <ul class="list-inline">
                                        <li>
                                            <strong>Duración</strong>
                                            {{ a.duracion }}
                                        </li>
                                        <li>
                                            <strong>Fecha de Inicio</strong>
                                            {{ a.fecha_inicio }}
                                        </li>
                                         <li>
                                            <strong>Anexo1</strong>
                                            <a href="/media/{{ a.file }}" target="_blank">Descargar</a>
                                        </li>
                                    </ul>
                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                        <i class="bi bi-x"></i>
                                        Close Project
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
                    {% endfor %}
                </div>
            </div>
        </section>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block 'contenido' %}
        <!-- Portfolio Grid-->
        <section class="page-section bg-light" id="portfolio">
            <div class="container">
            <div class="text-center">
{#                    <h5 class="section-heading text-uppercase">#}
{#                        <ol>#}
{#                        {% for m in name %}#}
{#                            <li>{{ m }}</li>#}
{#                        {% endfor %}#}
{#                        </ol>#}
{#                    </h5>#}
                </div>
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Proyectos</h2>
                </div>
                <div class="row">
                    {% for a in proyecto_list %}
                    {% if  a.programa == null %}
                    <div class="col-lg-4 col-sm-6 mb-4">
                        <!-- Portfolio item 1-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal{{ a.id }}">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="bi bi-search"></i></div>
                                </div>
                               {% if  a.imagen == " " %}
                                      <img class="img-fluid d-block mx-auto" style="height: 250px" src="/media/proyecto/proyecto.jpg" alt="..." />
                                    {% else %}
                                        <img class="img-fluid d-block mx-auto" style="height: 250px" src="/media/{{ a.imagen }}" alt="..." />
                                    {% endif %}
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">{{ a.nombre }}</div>
                            </div>
                        </div>
                    </div>
                         {% endif %}
                    <div class="portfolio-modal modal fade" id="portfolioModal{{ a.id }}" tabindex="-1" role="dialog" aria-hidden="true">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="close-modal" data-bs-dismiss="modal"><img src="{% static 'agency/assets/img/close-icon.svg' %}" alt="Close modal" /></div>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <div class="modal-body">
                                    <!-- Project details-->
                                    <h2 class="text-uppercase">{{ a.nombre}}</h2>
                                     <img class="img-fluid d-block mx-auto" src="/media/proyecto/proyecto.jpg" alt="..." />
                                    <p>{{ a.descrip }}</p>
                                    <ul class="list-inline">
                                        <li>
                                            <strong>Duración</strong>
                                            {{ a.duracion }}
                                        </li>
                                        <li>
                                            <strong>Fecha de Inicio</strong>
                                            {{ a.fecha_inicio }}
                                        </li>
                                         <li>
                                            <strong>Anexo1</strong>
                                            <a href="/media/{{ a.file }}" target="_blank">Descargar</a>
                                        </li>
                                    </ul>
                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                        <i class="bi bi-x"></i>
                                        Close Project
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    <!--   DESDE AQUI LOS SERVICIOS-->
         <section class="page-section bg-light" id="servicios">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Servicios</h2>
                </div>
                <div class="row">
                    {% for a in servicios  %}

                    <div class="col-lg-4 col-sm-6 mb-4">
                        <!-- Servicio item 1-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#servicioModal{{ a.id }}">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="bi bi-search"></i></div>
                                </div>

                                      <img class="img-fluid d-block mx-auto" style="height: 250px" src="/media/servicio/images/ser.jpg" alt="..." />

                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">{{ a.nombre }}</div>
                            </div>
                        </div>
                    </div>

                    <div class="portfolio-modal modal fade" id="servicioModal{{ a.id }}" tabindex="-1" role="dialog" aria-hidden="true">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="close-modal" data-bs-dismiss="modal"><img src="{% static 'agency/assets/img/close-icon.svg' %}" alt="Close modal" /></div>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <div class="modal-body">
                                    <!-- Serv details-->
                                    <h2 class="text-uppercase">{{ a.nombre}}</h2>
                                     <img class="img-fluid d-block mx-auto" src="/media/servicio/images/ser.jpg" alt="..." />
                                    <p>{{ a.descrip }}</p>
                                    <ul class="list-inline">

                                         <li>

                                            <a href="/media/servicio/documento/{{ a.file }}" target="_blank">>Diseño del Servicio</a>
                                        </li>
                                    </ul>
                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                        <i class="bi bi-x"></i>
                                        Close Project
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
                    {% endfor %}
                </div>
            </div>
         </section>
    <section class="page-section bg-light" id="encuentros">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Encuentros</h2>
                </div>
                <div class="row">
                    {% for a in object_list %}
                    {% if  a.programa == null %}
                    <div class="col-lg-4 col-sm-6 mb-4">
                        <!-- Portfolio item 1-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal{{ a.id }}">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="bi bi-search"></i></div>
                                </div>
                               {% if  a.imagen == " " %}
                                      <img class="img-fluid d-block mx-auto" style="height: 250px" src="/media/proyecto/proyecto.jpg" alt="..." />
                                    {% else %}
                                        <img class="img-fluid d-block mx-auto" style="height: 250px" src="/media/{{ a.imagen }}" alt="..." />
                                    {% endif %}
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">{{ a.nombre }}</div>
                            </div>
                        </div>
                    </div>
                         {% endif %}
                    <div class="portfolio-modal modal fade" id="portfolioModal{{ a.id }}" tabindex="-1" role="dialog" aria-hidden="true">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="close-modal" data-bs-dismiss="modal"><img src="{% static 'agency/assets/img/close-icon.svg' %}" alt="Close modal" /></div>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <div class="modal-body">
                                    <!-- Project details-->
                                    <h2 class="text-uppercase">{{ a.nombre}}</h2>
                                     <img class="img-fluid d-block mx-auto" src="/media/proyecto/proyecto.jpg" alt="..." />
                                    <p>{{ a.descrip }}</p>
                                    <ul class="list-inline">
                                        <li>
                                            <strong>Duración</strong>
                                            {{ a.duracion }}
                                        </li>
                                        <li>
                                            <strong>Fecha de Inicio</strong>
                                            {{ a.fecha_inicio }}
                                        </li>
                                         <li>
                                            <strong>Anexo1</strong>
                                            <a href="/media/{{ a.file }}" target="_blank">Descargar</a>
                                        </li>
                                    </ul>
                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                        <i class="bi bi-x"></i>
                                        Close Project
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
                    {% endfor %}
                </div>
            </div>
    </section>

{% endblock %}

templates/proyectos.html
{% extends 'base.html' %}
{% load static %}
{% block 'contenido' %}
        <!-- Portfolio Grid-->
        <section class="page-section bg-light" id="portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Proyectos</h2>
                </div>
                <div class="row">
                    {% for a in proyecto_list %}

                    <div class="col-lg-4 col-sm-6 mb-4">
                        <!-- Portfolio item 1-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal{{ a.id }}">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="bi bi-search"></i></div>
                                </div>
                               {% if  a.imagen == " " %}
                                      <img class="img-fluid d-block mx-auto" style="height: 250px" src="/media/proyecto/proyecto.jpg" alt="..." />
                                    {% else %}
                                        <img class="img-fluid d-block mx-auto" style="height: 250px" src="/media/{{ a.imagen }}" alt="..." />
                                    {% endif %}
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">{{ a.nombre }}</div>
                            </div>
                        </div>
                    </div>

                    <div class="portfolio-modal modal fade" id="portfolioModal{{ a.id }}" tabindex="-1" role="dialog" aria-hidden="true">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="close-modal" data-bs-dismiss="modal"><img src="{% static 'agency/assets/img/close-icon.svg' %}" alt="Close modal" /></div>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <div class="modal-body">
                                    <!-- Project details-->
                                    <h2 class="text-uppercase">{{ a.nombre}}</h2>
                                     <img class="img-fluid d-block mx-auto" src="/media/proyecto/proyecto.jpg" alt="..." />
                                    <p>{{ a.descrip }}</p>
                                    <ul class="list-inline">
                                        <li>
                                            <strong>Duración</strong>
                                            {{ a.duracion }}
                                        </li>
                                        <li>
                                            <strong>Fecha de Inicio</strong>
                                            {{ a.fecha_inicio }}
                                        </li>
                                         <li>
                                            <strong>Anexo1</strong>
                                            <a href="/media/{{ a.file }}" target="_blank">Descargar</a>
                                        </li>
                                    </ul>
                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                        <i class="bi bi-x"></i>
                                        Close Project
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endfor %}
                </div>
            </div>
        </section>
        <canvas id="grafica"></canvas>
        <script>
        // Obtener una referencia al elemento canvas del DOM
const $grafica = document.querySelector("#grafica");
// Las etiquetas son las que van en el eje X.

const etiquetas = [
    {% for b in object_list %}
    "{{ b.nombre }}",
    {% endfor %}
]
// Podemos tener varios conjuntos de datos. Comencemos con uno
const datosVentas2020 = {
    label: "Estado de terminacion de los proyectos",
    data: [
        {% for c in estado %}
        {{ c }},
        {% endfor %}
    ], // La data es un arreglo que debe tener la misma cantidad de valores que la cantidad de etiquetas
    backgroundColor: 'rgba(54, 162, 235, 0.2)', // Color de fondo
    borderColor: 'rgba(54, 162, 235, 1)', // Color del borde
    borderWidth: 1,// Ancho del borde
};
new Chart($grafica, {
    type: 'bar',// Tipo de gráfica
    data: {
        labels: etiquetas,
        datasets: [
            datosVentas2020,
            // Aquí más datos...
        ]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }],
        },
    }
});
        </script>
{% endblock %}